config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root to: 'main#index'

  resources :projects, only: %i[index show] do
    resources :time_slots, only: :index
  end
  resources :tools, only: %i[index show] do
    resources :time_slots, only: :index
    member do
      get :versions
    end
  end
  resources :time_slots, only: :index
  resources :pages, only: %i[index show]
  resources :companies, only: %i[index]

  get '/admin' => redirect('/admin/projects')
  namespace :admin do
    concern :deletable do
      get :delete, on: :member
    end
    resources :projects, concerns: %i[deletable] do
      resources :screenshots, concerns: %i[deletable]
      resources :tool_projects, concerns: %i[deletable]
      resources :time_slots, concerns: %i[deletable]
    end
    resources :tools, concerns: %i[deletable]
    resources :pages, concerns: %i[deletable]
    resources :tool_types, concerns: %i[deletable]
    resources :contacts, concerns: %i[deletable]
    resources :companies, concerns: %i[deletable]
  end

  get '/*path' => 'application#not_found'
end
# rubocop:enable Metrics/BlockLength

app/models/tool.rb
# frozen_string_literal: true

class Tool < ApplicationRecord
  include TotalPeriod

  validates :name, presence: true, uniqueness: true

  belongs_to :tool_type

  has_many :tool_projects, dependent: :destroy
  has_many :projects, through: :tool_projects
  has_many :time_slots, through: :projects

  delegate :name, to: :tool_type, prefix: true, allow_nil: true

  def self.available_for(tool_project)
    used_tools = tool_project.project.tools.where.not(id: tool_project.tool_id)
    where.not(id: used_tools.select(Tool.arel_table[:id]))
  end

  def versions
    tool_projects.includes(project: [:time_slots]).group_by(&:version).map do |(version, tool_projects)|
      period = tool_projects.sum(&:project_total_period)
      Version.new(version, period)
    end
  end
end

app/models/tool/version.rb
# frozen_string_literal: true

class Tool
  class Version
    attr_reader :label, :period

    def initialize(label, period)
      @label = label
      @period = period
    end

    def ==(other)
      label == other.label && period == other.period
    end

    def color
      "##{Digest::SHA1.hexdigest(label).first(6)}"
    end
  end
end

app/models/tool_type.rb
# frozen_string_literal: true

class ToolType < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :tools, dependent: :nullify
end

app/controllers/admin/tools_controller.rb
# frozen_string_literal: true

module Admin
  class ToolsController < Admin::BaseController
    respond_to :html

    before_action :find_tool, only: %i[show edit update delete destroy]

    def new
      @tool = Tool.new
      respond_with @tool
    end

    def index
      @tools = Tool.order(:name).preload(:tool_type).all
      respond_with @tools
    end

    def create
      @tool = Tool.create(tool_params)
      respond_with @tool, location: [:admin, @tool]
    end

    def show
      respond_with @tool
    end

    def edit
      respond_with @tool
    end

    def update
      @tool.update(tool_params)
      respond_with @tool, location: [:admin, @tool]
    end

    def delete
      respond_with @tool
    end

    def destroy
      @tool.destroy
      respond_with @tool, location: :admin_tools
    end

    protected

    def tool_params
      params.require(:tool).permit(:name, :tool_type_id)
    end

    def find_tool
      @tool = Tool.find(params[:id])
    end
  end
end

app/controllers/tools_controller.rb
# frozen_string_literal: true

class ToolsController < ApplicationController
  respond_to :html, only: %i[index show]
  respond_to :svg, only: %i[versions]

  before_action :find_tool, only: %i[show versions]

  def index
    @tools = Tool.includes(:time_slots).preload(:tool_type).order(:name).all
    respond_with @tools
  end

  def show
    respond_with @tool
  end

  def versions
    @versions = @tool.versions
    respond_with @versions
  end

  protected

  def find_tool
    @tool = Tool.find(params[:id].to_i)
  end
end

app/views/tools/_tool.html.slim
article.col-md-4.col-sm-6.col-xs-12
  h3 = link_to tool.name, tool

  p = format_period(tool.total_period)

app/views/tools/_versions.html.slim
table.table
  thead
    tr
      th
      th = t('.version')
      th = t('.period')
      th = t('.proportion')
  tbody
    - tool.versions.each do |version|
      tr
        td bgcolor=version.color
          | &nbsp;
        td = version.label
        td = format_period(version.period)
        td = format_period_proportion(version.period, tool.total_period)

app/views/tools/index.html.slim
h1 = t('.tools')

- @tools.group_by(&:tool_type_id).each do |_, type_tools|
  h2 = type_tools.first.tool_type_name || t(".other_tool_type")

  .row
    - type_tools.each do |tool|
      = render tool

app/views/tools/show.html.slim
h1 = t('.tool', tool_name: @tool.name, default: 'Tool "%{tool_name}"')

h2 = t('.versions')
.row
  .col-md-8
    = render 'tools/versions', tool: @tool

  .col-md-4
    = image_tag versions_tool_path(@tool, format: 'svg'),
      title: t('.versions', default: 'Versions'),
      width: '100%'

h2 = t('.time_slots')
= timeline_widget tool_time_slots_path(@tool, format: 'json')

h2 = t('.total_period')
p = format_period(@tool.total_period)

h2 = t('.projects')
ul.list-inline
  - @tool.tool_projects.each do |tool_project|
    li = link_to tool_project.project.name, tool_project.project

app/views/tools/versions.svg.slim
svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 100 100" width="100px" height="100px"
  - render_version_graphic @versions