config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root to: 'main#index'

  resources :projects, only: %i[index show] do
    resources :time_slots, only: :index
  end
  resources :tools, only: %i[index show] do
    resources :time_slots, only: :index
    member do
      get :versions
    end
  end
  resources :time_slots, only: :index
  resources :pages, only: %i[index show]
  resources :companies, only: %i[index]

  get '/admin' => redirect('/admin/projects')
  namespace :admin do
    concern :deletable do
      get :delete, on: :member
    end
    resources :projects, concerns: %i[deletable] do
      resources :screenshots, concerns: %i[deletable]
      resources :tool_projects, concerns: %i[deletable]
      resources :time_slots, concerns: %i[deletable]
    end
    resources :tools, concerns: %i[deletable]
    resources :pages, concerns: %i[deletable]
    resources :tool_types, concerns: %i[deletable]
    resources :contacts, concerns: %i[deletable]
    resources :companies, concerns: %i[deletable]
  end

  get '/*path' => 'application#not_found'
end
# rubocop:enable Metrics/BlockLength

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  include TotalPeriod

  validates :name, presence: true

  has_many :screenshots, dependent: :destroy
  has_many :tool_projects, dependent: :destroy
  has_many :tools, through: :tool_projects
  has_many :time_slots, dependent: :destroy
  belongs_to :company, optional: true

  delegate :name, to: :company, prefix: true, allow_nil: true
end

app/controllers/admin/projects_controller.rb
# frozen_string_literal: true

module Admin
  class ProjectsController < Admin::BaseController
    respond_to :html

    before_action :find_project, only: %i[show edit update delete destroy]

    def index
      @projects = Project.order(:name).all
    end

    def new
      @project = Project.new
    end

    def show; end

    def create
      @project = Project.new(project_params)
      if @project.save
        redirect_to [:admin, @project]
      else
        render :new
      end
    end

    def edit; end

    def update
      if @project.update(project_params)
        redirect_to [:admin, @project]
      else
        render :edit
      end
    end

    def delete; end

    def destroy
      @project.destroy
      redirect_to admin_projects_path
    end

    private

    def find_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :description, :url, :role, :company_id)
    end
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  respond_to :html, :json

  def show
    @project = Project.find(params[:id])
    respond_with @project
  end

  def index
    @projects = Project.order(:name).all
    respond_with @projects
  end
end

app/views/projects/_project.html.slim
article
  h2= link_to project.name, project
  p= link_to project.url, project.url
  p= simple_format project.description

app/views/projects/index.html.slim
h1= t('.projects')
= render @projects

app/views/projects/show.html.slim
h1
  = t '.project', project_name: @project.name, default: 'Project "%{project_name}"'
  - if @project.url?
    |  (#{link_to(@project.url, )})

section
  h2 = t('.description')
  = simple_format @project.description

section
  h2 = t('.role')
  = simple_format @project.role

- if @project.company_name
  section
    h2 = t('.company_name')
    = @project.company_name

section
  h2 = t('.screenshots')
  - if @project.screenshots.any?
    .row = render partial: 'projects/show/screenshot', collection: @project.screenshots
  - else
    p = t('.no_screenshots')

section
  h2 = t('.tools')
  - if @project.tool_projects.any?
    ul.list-inline = render partial: 'projects/show/tool_project', collection: @project.tool_projects.with_tools
  - else
    p = t('.no_tools')

section
  h2 = t('.time_slots')
  = timeline_widget project_time_slots_path(@project, format: 'json')


section
  h2 = t('.total_period')
  p = format_period @project.total_period